using Content.Client.UserInterface.Controls;
using Content.Shared._CD.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CD.Records.UI;

// TODO: Add a scrollbar to this. I tried for over an hour and I could not get it to work in a way that I liked.

[GenerateTypedNameReferences]
public sealed partial class RecordEntryViewPopup : FancyWindow
{
    // We don't permit headings because it looks ugly
    private static readonly Type[] AllowedTags =
    {
        typeof(BoldItalicTag),
        typeof(BoldTag),
        typeof(BulletTag),
        typeof(ColorTag),
        typeof(ItalicTag)
    };

    public RecordEntryViewPopup()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetContents(PlayerProvidedCharacterRecords.RecordEntry entry)
    {
        EntryTitle.SetMessage(entry.Title);
        EntryInvolved.SetMessage(entry.Involved);
        EntryDesc.SetMessage(FormattedMessage.FromMarkupPermissive(entry.Description.Trim()), AllowedTags);
    }
}
