using Content.Shared._CD.Records;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.Records.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordEditorGui : Control
{
    private readonly Action<CharacterRecords> _updateProfileRecords;
    private CharacterRecords _records = default!;

    public RecordEditorGui(Action<CharacterRecords> updateProfileRecords)
    {
        RobustXamlLoader.Load(this);
        _updateProfileRecords = updateProfileRecords;

        #region General

        HeightEdit.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newHeight))
                return;
            UpdateImperialHeight(newHeight);
            UpdateRecords(_records.WithHeight(newHeight));
        };

        WeightEdit.OnTextChanged += args =>
        {
            if (!int.TryParse(args.Text, out var newWeight))
                return;
            UpdateImperialWeight(newWeight);
            UpdateRecords(_records.WithWeight(newWeight));
        };

        ContactNameEdit.OnTextChanged += args =>
        {
            UpdateRecords(_records.WithContactName(args.Text));
        };

        ContactNumberEdit.OnTextChanged += args =>
        {
            UpdateRecords(_records.WithContactNumber(args.Text));
        };

        #endregion

        #region Employment

        WorkAuthCheckBox.OnToggled += args =>
        {
            UpdateRecords(_records.WithWorkAuth(args.Pressed));
        };

        #endregion

        #region Security

        SecurityClearanceSelector.AddItem(
            Loc.GetString("humanoid-profile-editor-cd-records-sec-clearance-standard"),
            (int)CharacterRecords.ClearanceLevel.Standard);
        SecurityClearanceSelector.AddItem(
            Loc.GetString("humanoid-profile-editor-cd-records-sec-clearance-sec"),
            (int)CharacterRecords.ClearanceLevel.Security);
        SecurityClearanceSelector.AddItem(
            Loc.GetString("humanoid-profile-editor-cd-records-sec-clearance-command"),
            (int)CharacterRecords.ClearanceLevel.Command);
        SecurityClearanceSelector.AddItem(
            Loc.GetString("humanoid-profile-editor-cd-records-sec-clearance-high-command"),
            (int)CharacterRecords.ClearanceLevel.HighCommand);

        SecurityClearanceSelector.OnItemSelected += args =>
        {
            SecurityClearanceSelector.SelectId(args.Id);
            UpdateRecords(
                _records.WithSecurityClearance((CharacterRecords.ClearanceLevel) args.Id));
        };

        IdentifyingFeaturesEdit.OnTextChanged += args =>
        {
            UpdateRecords(_records.WithIdentifyingFeatures(args.Text));
        };

        #endregion

        #region Medical

        AllergiesEdit.OnTextChanged += args =>
        {
            UpdateRecords(_records.WithAllergies(args.Text));
        };

        DrugAllergiesEdit.OnTextChanged += args =>
        {
            UpdateRecords(_records.WithDrugAllergies(args.Text));
        };

        PostmortemEdit.OnTextChanged += args =>
        {
            UpdateRecords(_records.WithPostmortemInstructions(args.Text));
        };

        #endregion

        #region Entries

        EntryEditorTabs.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-cd-records-employment"));
        EntryEditorTabs.SetTabTitle(1, Loc.GetString("department-Medical"));
        EntryEditorTabs.SetTabTitle(2, Loc.GetString("department-Security"));

        EmploymentEntrySelector.OnUpdateEntries += args =>
        {
            UpdateRecords(_records.WithEmploymentEntries(args.Entries));
        };

        MedicalEntrySelector.OnUpdateEntries += args =>
        {
            UpdateRecords(_records.WithMedicalEntries(args.Entries));
        };

        SecurityEntrySelector.OnUpdateEntries += args =>
        {
            UpdateRecords(_records.WithSecurityEntries(args.Entries));
        };

        #endregion
    }

    public void Update(HumanoidCharacterProfile profile)
    {
        _records = profile.CDCharacterRecords ?? CharacterRecords.DefaultRecords();
        EmploymentEntrySelector.UpdateContents(_records.EmploymentEntries);
        MedicalEntrySelector.UpdateContents(_records.MedicalEntries);
        SecurityEntrySelector.UpdateContents(_records.SecurityEntries);
        UpdateWidgets();
    }

    private void UpdateRecords(CharacterRecords records)
    {
        records.EnsureValid();
        _records = records;
        _updateProfileRecords(_records);
        UpdateWidgets();
    }

    private void UpdateWidgets()
    {
        HeightEdit.SetText(_records.Height.ToString());
        UpdateImperialHeight(_records.Height);
        WeightEdit.SetText(_records.Weight.ToString());
        UpdateImperialWeight(_records.Weight);
        ContactNameEdit.SetText(_records.EmergencyContactName);
        ContactNumberEdit.SetText(_records.EmergencyContactNumber);

        WorkAuthCheckBox.Pressed = _records.HasWorkAuthorization;

        SecurityClearanceSelector.SelectId((int)_records.SecurityClearance);
        IdentifyingFeaturesEdit.SetText(_records.IdentifyingFeatures);

        AllergiesEdit.SetText(_records.Allergies);
        DrugAllergiesEdit.SetText(_records.DrugAllergies);
        PostmortemEdit.SetText(_records.PostmortemInstructions);
    }

    private void UpdateImperialHeight(int newHeight)
    {
        int heightIn = (int) Math.Round(newHeight * 0.3937007874 /* cm to in*/);
        HeightImperialLabel.Text = $"({heightIn / 12}'{heightIn % 12}'')";
    }
    private void UpdateImperialWeight(int newWeight)
    {
        int weightLbs = (int) Math.Round(newWeight * 2.2046226218);
        WeightImperialLabel.Text = $"({weightLbs} lbs)";
    }
}
