using Content.Client.UserInterface.Controls;
using Content.Shared._CD.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.Records.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordViewEntryPopup : FancyWindow
{
    private readonly Type[] _allowedTags =
    {
        typeof(BoldItalicTag),
        typeof(BoldTag),
        typeof(BulletTag),
        typeof(ColorTag),
        typeof(HeadingTag),
        typeof(ItalicTag)
    };

    public RecordViewEntryPopup()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetContents(CharacterRecords.RecordEntry entry)
    {
        EntryTitle.Text = entry.Title;
        EntryInvolved.Text = entry.Involved;
        // I don't think the rich text is fully working.
        EntryDesc.SetMessage(entry.Description, _allowedTags);
    }
}
