using Content.Shared._CD.Records;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CD.Records.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordEntryEditPopup : DefaultWindow
{
    public RecordEntryEditPopup(bool readOnly = false)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (!readOnly)
        {
            DescriptionEdit.Placeholder =
                new Rope.Leaf(Loc.GetString("cd-records-entry-edit-popup-description-placeholder"));

            SaveButton.OnPressed += _ =>
            {
                Close();
            };
        }
        else
        {
            SaveButton.Visible = false;
            TitleEdit.Editable = false;
            InvolvedEdit.Editable = false;
            DescriptionEdit.Editable = false;
        }

    }

    public CharacterRecords.RecordEntry GetContents()
    {
        string desc = Rope.Collapse(DescriptionEdit.TextRope).Trim();
        return new CharacterRecords.RecordEntry(TitleEdit.Text, InvolvedEdit.Text, desc);
    }

    public void SetContents(CharacterRecords.RecordEntry entry)
    {
        TitleEdit.Text = entry.Title;
        InvolvedEdit.Text = entry.Involved;
        DescriptionEdit.TextRope = new Rope.Leaf(entry.Description);
    }
}
