using Content.Shared._CD.Records;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CD.Records.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordEditorGui : Control
{
    public RecordEditorGui()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(HumanoidCharacterProfile profile)
    {
        TempRecordTextInput.TextRope = new Rope.Leaf(profile.CDCharacterRecords?.Allergies ?? "TEST");
    }
}
