- type: entity
  name: stun sabre
  parent: Stunbaton
  id: StunSabre
  description: A variant of the stunbaton, designed to look like a sabre or longsword
  components:
  - type: Sprite
    sprite: _CD/Objects/Weapons/Melee/stunsabre.rsi
    layers:
    - state: stunsabre_off
      map: [ "enum.ToggleVisuals.Layer" ]
  - type: Tag
    tags:
    - StunSabre
  - type: Appearance
  - type: GenericVisualizer
    visuals:
     enum.ToggleVisuals.Toggled:
        enum.ToggleVisuals.Layer:
          True: {state: stunsabre_on}
          False: {state: stunsabre_off}