using Content.Shared._CD.CryoSleep;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.CryoSleep;

[GenerateTypedNameReferences]
public sealed partial class AcceptCryoWindow : DefaultWindow
{
    public event Action<AcceptCryoUiButton>? OnChoice;

    public AcceptCryoWindow()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ =>
        {
            OnChoice?.Invoke(AcceptCryoUiButton.Accept);
            Close();
        };

        DenyButton.OnPressed += _ =>
        {
            OnChoice?.Invoke(AcceptCryoUiButton.Deny);
            Close();
        };
    }
}
