using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.CryoSleep;

[GenerateTypedNameReferences]
public sealed partial class LostAndFoundItemControl : BoxContainer
{
    public LostAndFoundItemControl(string slotName, string itemName)
    {
        RobustXamlLoader.Load(this);

        // Replace spaces with underscores so that held items dont troll us
        var locKey = $"lost-and-found-slot-{slotName.ToLower().Replace(" ", "_")}";
        var localizedSlot = Loc.GetString(locKey);

        SlotLabel.SetMarkup(localizedSlot);
        ItemLabel.Text = itemName;
    }
}
