using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class AiShellSelectionMenu : FancyWindow
{
    public Action? JumpToShell;
    public Action? EnterShell;

    [Dependency] private readonly IEntityManager _ent = default!;

    public AiShellSelectionMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(List<EntityUid> shells)
    {

    }
}

