using Content.Client.Administration.Managers;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client._CD.Admin.UI.CharacterPanel;

[GenerateTypedNameReferences]
public sealed partial class CharacterPanel : FancyWindow
{
    private readonly IClientAdminManager _adminManager;

    public NetUserId TargetPlayerID;
    public string? TargetPlayer;

    public CharacterPanel(IClientAdminManager adminManager)
    {
        RobustXamlLoader.Load(this);
        _adminManager = adminManager;
    }

    public void SetPlayer(string player)
    {
        Title = Loc.GetString("cd-characterpanel-title", ("player", player));
        PlayerName.Text = Loc.GetString("cd-characterpanel-player", ("player", player));
    }

    public void SetCharacterDescription(string? description)
    {
        if (description == null)
            Loc.GetString("cd-characterpanel-missing-description");
        else
            Loc.GetString("cd-characterpanel-character-description", ("characterDescription", description));
    }
}
