using System.Linq;
using Content.Shared._CD.Silicons;
using Content.Shared._CD.Silicons.Borgs;
using Content.Shared.Silicons.Borgs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CD.Silicons.Borgs.UI;

[GenerateTypedNameReferences]
public sealed partial class ChassisSpriteSelection : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public BorgSubtypePrototype? SubtypePrototype;
    public event Action? SubtypeSelected;

    public ChassisSpriteSelection()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(BorgTypePrototype borgTypePrototype)
    {
        OptionsContainer.RemoveAllChildren();

        var buttonGroup = new ButtonGroup();
        List<Button> buttons = new List<Button>();
        buttons.Add(CreateDefaultSubtypeButton(borgTypePrototype, buttonGroup));

        foreach (var subtypePrototype in _proto.EnumeratePrototypes<BorgSubtypePrototype>())
        {
            // Only add subtypes of the current selected 'main' borg type (engineering, medical, etc.)
            if(subtypePrototype.ParentType != borgTypePrototype.ID)
                continue;

            var button = new Button
            {
                Text = subtypePrototype.ID,
                Group = buttonGroup,
            };

            button.OnPressed += _ =>
            {
                SubtypePrototype = subtypePrototype;
                SubtypeSelected?.Invoke();
            };

            buttons.Add(button);
        }

        foreach (var button in buttons)
        {
            OptionsContainer.AddChild(button);
        }
    }

    private Button CreateDefaultSubtypeButton(BorgTypePrototype borgTypePrototype, ButtonGroup group)
    {
        var button = new Button
        {
            Text = "default",
            Group = group,
        };

        button.OnPressed += _ =>
        {
            SubtypePrototype = null;
            SubtypeSelected?.Invoke();
        };

        return button;
    }
}

