- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Gemini
  - Marathon
  - Oasis
  - Omega #CD addition
  - Packed
  - Plasma
  - Reach
  - Ferrous
  # - Exo # CD Derotate
  - Snowball
