using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;
using Robust.Shared.Utility;

namespace Content.Client._CD.Ghostrespawn;

[GenerateTypedNameReferences]
public sealed partial class GhostRespawnRulesWindow : FancyWindow
{
    [Dependency] private readonly IConsoleHost _consoleHost = default!;

    private readonly RichTextLabel _rulesLabel = new() { Margin = new Thickness(5, 5, 5, 5) };

    public GhostRespawnRulesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var message = new FormattedMessage();
        message.AddMarkupOrThrow(Loc.GetString("ghost-respawn-rules-window-rules"));
        _rulesLabel.SetMessage(message);
        RulesContainer.AddChild(_rulesLabel);
        _rulesLabel.SetPositionFirst();

        ConfirmRespawnButton.OnPressed += _ =>
        {
            _consoleHost.ExecuteCommand("ghostrespawn");
            Close();
        };
    }
}
