using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.Telephone;

[GenerateTypedNameReferences]
public sealed partial class TelephoneWindow : DefaultWindow
{
    public TelephoneWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
