using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.Admin.UI;

[GenerateTypedNameReferences]
public sealed partial class EventPreferencesPanel : DefaultWindow
{
    public EventPreferencesPanel()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetDetails(string username, HumanoidCharacterProfile currentPreferences)
    {
        PlayerLabel.Text = Loc.GetString("cd-eventpreferencepanel-player", ("player", username));
        CharacterLabel.Text = Loc.GetString(
            "cd-eventpreferencepanel-character",
            ("characterName", currentPreferences.Name)
            );
    }

    public void SetPreferenceList(HumanoidCharacterProfile userPreferences, IEnumerable<AntagPrototype> listablePreferences)
    {
        EventPreferenceControl.SetPreferenceList(userPreferences, listablePreferences);
    }
}
