using Content.Client.Administration.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.Admin.UI;

[GenerateTypedNameReferences]
public sealed partial class EventPreferences : Control
{
    private readonly IClientAdminManager _adminManager;
    public EventPreferences(IClientAdminManager adminManager)
    {
        RobustXamlLoader.Load(this);
        _adminManager = adminManager;
    }

    public void SetPreferenceList(bool[] preferences)
    {

    }
}
