using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CD.Admin.UI;

[GenerateTypedNameReferences]
public sealed partial class EventPreferencesPanel : DefaultWindow
{
    public EventPreferencesPanel()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Sets the displayed username of the current player alongside their current selected character's name
    /// </summary>
    /// <param name="username">Player's username</param>
    /// <param name="currentPreferences">Profile preference to fetch the character name from</param>
    public void SetDetails(string username, HumanoidCharacterProfile currentPreferences, List<ProtoId<AntagPrototype>> listablePreferences)
    {
        PlayerLabel.Text = Loc.GetString("cd-eventpreferencepanel-player", ("player", username));
        CharacterLabel.Text = Loc.GetString(
            "cd-eventpreferencepanel-character",
            ("characterName", currentPreferences.Name)
            );

        EventPreferenceControl.SetPreferenceList(currentPreferences, listablePreferences);
    }
}
