using Content.Client.Administration.Managers;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CD.Admin.UI;

[GenerateTypedNameReferences]
public sealed partial class EventPreferences : Control
{
    private readonly IClientAdminManager _adminManager;
    public EventPreferences(IClientAdminManager adminManager)
    {
        RobustXamlLoader.Load(this);
        _adminManager = adminManager;
    }

    public void SetPreferenceList(HumanoidCharacterProfile preferences, IEnumerable<AntagPrototype> listablePreferences)
    {
        foreach (var listablePreference in listablePreferences)
        {
            var label = new Label();
            Color color = Color.Red;
            if (preferences.AntagPreferences.Contains(listablePreference))
                color = Color.Green;

            label.Text = Loc.GetString(listablePreference.Name);
            label.Modulate = color;

            EventPrefList.AddChild(label);
        }
    }
}
