#Sheriff Hat
- type: loadout
  id: HeadofSecuritySheriffHat
  equipment: 
    head: ClothingHeadHatHossheriffhat

# Headset
- type: loadout
  id: HeadofSecurityHeadset
  equipment:
    ears: ClothingHeadsetHoS

- type: loadout
  id: HeadofSecurityHeadsetAlt
  equipment:
    ears: ClothingHeadsetAltSecurity
