- !type:CDSpawnEntityMapPatch
  worldPosition: -9.228987,-3.9148211
  id: LockerLostAndFound
- !type:CDSpawnEntityMapPatch
  worldRotation: 1.5707963267948966 rad
  worldPosition: -11.228987,-4.914821
  id: ComputerStationRecords
