using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Serilog;

namespace Content.Client._CD.Silicon.UI;

[GenerateTypedNameReferences]
public partial class ChassisSpriteSelection : Control
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    public ChassisSpriteSelection()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }
}
